#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform PushConstants {
    uint elementCount;
    uint iterationCount;
} pushConstants;

layout(binding = 0) readonly buffer IndexBuffer {
    uint nextIndex[];
} indexBuffer;

layout(binding = 1) readonly buffer ValueBuffer {
    uint values[];
} valueBuffer;

layout(binding = 2) writeonly buffer OutputBuffer {
    uint outputData[];
} outputBuffer;

void main() {
    uint gid = gl_GlobalInvocationID.x;
    uint cursor = gid % pushConstants.elementCount;
    uint accum = 0;

    for (uint i = 0; i < pushConstants.iterationCount; ++i) {
        cursor = indexBuffer.nextIndex[cursor];
        accum ^= valueBuffer.values[cursor] + i;
    }

    outputBuffer.outputData[gid] = accum;
}
